# Generated by rust2rpm 12
# * https://github.com/dtolnay/proc-macro-hack/issues/47
%bcond_with check
%global debug_package %{nil}

%global crate proc-macro-nested

Name:           rust-%{crate}
Version:        0.1.3
Release:        2%{?dist}
Summary:        Support for nested proc-macro-hack invocations

# Upstream license specification: MIT/Apache-2.0
# * https://github.com/dtolnay/proc-macro-hack/pull/48
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/proc-macro-nested
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Support for nested proc-macro-hack invocations.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Dec 13 23:48:28 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.3-1
- Initial package
